/**
 * Auto-updating documentation script for the ecocan repo.
 * Plain ESM JavaScript – no TypeScript runtime needed.
 *
 * Behavior:
 *   - SITEMAP.md       → always regenerated (scans page.tsx|ts|jsx|js under app/)
 *   - CODEBASE-MAP.md  → always regenerated (walks full directory tree)
 *   - ROLLBACK.md      → appends entry only when GITHUB_SHA env var is set
 *   - VERCEL.md        → appends entry when GITHUB_SHA is present, using VERCEL_URL when available
 *
 * Usage:
 *   npm run docs:update
 */

import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Recursively walk a directory, yielding relative file paths. */
async function walk(dir, base = dir) {
  const results = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  const SKIP = new Set(['node_modules', '.next', '.git', 'dist', 'out', '.vercel']);
  for (const entry of entries) {
    if (SKIP.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    const rel = path.relative(base, full);
    if (entry.isDirectory()) {
      results.push(...(await walk(full, base)));
    } else {
      results.push(rel);
    }
  }
  return results;
}

/** Safely overwrite a file with the given content. */
async function write(filePath, content) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
  console.log(`  ✅  written: ${path.relative(ROOT, filePath)}`);
}

/** Read a file, returning empty string if it does not exist. */
async function readOrEmpty(filePath) {
  try {
    return await fs.readFile(filePath, 'utf8');
  } catch {
    return '';
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// SITEMAP.md  –  always regenerated
// ─────────────────────────────────────────────────────────────────────────────

async function generateSitemap() {
  console.log('\n📄  Generating SITEMAP.md …');

  const appDir = path.join(ROOT, 'app');
  const allFiles = await walk(appDir, appDir);
  const pageFiles = allFiles.filter(
    (f) => /page\.(tsx|ts|jsx|js)$/.test(f)
  );

  const toRoute = (f) => {
    let r = '/' + f.replace(/\/?page\.(tsx|ts|jsx|js)$/, '').replace(/\\/g, '/');
    return r.replace(/\/$/, '') || '/';
  };

  const routes = pageFiles.map(toRoute).sort();
  const staticRoutes = routes.filter((r) => !r.includes('['));
  const dynamicRoutes = routes.filter((r) => r.includes('['));

  const now = new Date().toISOString();

  let md = `# Sitemap\n\n`;
  md += `> Auto-generated by \`scripts/update-docs.mjs\` – last updated **${now}**\n`;
  md += `> Do **not** edit manually; regenerated on every push to \`main\`.\n\n`;

  md += `## Static Routes\n\n| Route | File |\n|-------|------| \n`;
  for (const route of staticRoutes) {
    const file = pageFiles.find((f) => toRoute(f) === route);
    md += `| \`${route}\` | \`app/${file}\` |\n`;
  }

  if (dynamicRoutes.length > 0) {
    md += `\n## Dynamic Routes\n\n| Route Pattern | File |\n|---------------|------| \n`;
    for (const route of dynamicRoutes) {
      const file = pageFiles.find((f) => toRoute(f) === route);
      md += `| \`${route}\` | \`app/${file}\` |\n`;
    }
  }

  md += `\n## Notes\n\n`;
  md += `- Route patterns containing \`[…]\` are dynamic segments resolved at runtime.\n`;
  md += `- An XML sitemap for SEO can be generated from this list via \`app/sitemap.ts\`.\n`;

  await write(path.join(ROOT, 'SITEMAP.md'), md);
}

// ─────────────────────────────────────────────────────────────────────────────
// CODEBASE-MAP.md  –  always regenerated
// ─────────────────────────────────────────────────────────────────────────────

async function generateCodebaseMap() {
  console.log('\n🗺️   Generating CODEBASE-MAP.md …');

  const allFiles = await walk(ROOT, ROOT);
  const groups = {};
  const topLevelFiles = [];

  for (const f of allFiles) {
    const parts = f.split(path.sep);
    if (parts.length === 1) {
      topLevelFiles.push(f);
    } else {
      const dir = parts[0];
      (groups[dir] = groups[dir] || []).push(f);
    }
  }

  const dirStats = Object.entries(groups)
    .map(([dir, files]) => ({ dir, count: files.length, files }))
    .sort((a, b) => a.dir.localeCompare(b.dir));

  const now = new Date().toISOString();

  let md = `# Codebase Map\n\n`;
  md += `> Auto-generated by \`scripts/update-docs.mjs\` – last updated **${now}**\n`;
  md += `> Do **not** edit manually; regenerated on every push to \`main\`.\n\n`;

  md += `## Stack Overview\n\n| Layer | Technology |\n|-------|-----------|\n`;
  md += `| Framework | Next.js 14 (App Router) |\n`;
  md += `| Language | TypeScript 5 + React 18 |\n`;
  md += `| Styling | Tailwind CSS 3 + Radix UI primitives |\n`;
  md += `| Animation | Framer Motion + Embla Carousel |\n`;
  md += `| Forms | react-hook-form + zod |\n`;
  md += `| Analytics | @vercel/analytics |\n`;
  md += `| Deployment | Vercel |\n\n`;

  md += `## Directory Structure\n\n`;
  for (const { dir, count, files } of dirStats) {
    md += `### \`${dir}/\` (${count} files)\n\n`;
    const subDirs = {};
    for (const f of files) {
      const parts = f.split(path.sep);
      if (parts.length >= 2) subDirs[parts[1]] = (subDirs[parts[1]] || 0) + 1;
    }
    if (Object.keys(subDirs).length > 0) {
      for (const [sub, cnt] of Object.entries(subDirs).sort())
        md += `- \`${dir}/${sub}\` – ${cnt} file${cnt !== 1 ? 's' : ''}\n`;
    } else {
      for (const f of files.sort()) md += `- \`${f}\`\n`;
    }
    md += '\n';
  }

  md += `## Data & Content Flow\n\n`;
  md += `1. **Routing** – Each folder under \`app/\` maps to a URL segment via Next.js App Router.\n`;
  md += `2. **Page composition** – Pages import persona content from \`components/contents/{persona}/\`.\n`;
  md += `3. **Shared layout** – \`app/layout.tsx\` wraps every page with Navbar and Footer.\n`;
  md += `4. **Design system** – \`components/ui/\` holds Radix + Tailwind primitives.\n`;
  md += `5. **Forms** – \`react-hook-form\` + \`zod\` schemas in \`components/shared/\`.\n`;
  md += `6. **Utilities** – Hooks in \`lib/\`; TypeScript models in \`types/\`.\n\n`;

  await write(path.join(ROOT, 'CODEBASE-MAP.md'), md);
}

// ─────────────────────────────────────────────────────────────────────────────
// ROLLBACK.md  –  append only when GITHUB_SHA is present
// ─────────────────────────────────────────────────────────────────────────────

async function updateRollback() {
  const sha = process.env.GITHUB_SHA;
  if (!sha) {
    console.log('\n⏭️   ROLLBACK.md – skipped (GITHUB_SHA not set)');
    return;
  }
  console.log('\n🔄  Updating ROLLBACK.md …');

  const filePath = path.join(ROOT, 'ROLLBACK.md');
  let content = await readOrEmpty(filePath);

  const shortSha = sha.slice(0, 7);
  const shaUrl = `https://github.com/rauell1/ecocan/commit/${sha}`;
  const branch = process.env.GITHUB_REF_NAME || 'unknown';
  const actor = process.env.GITHUB_ACTOR || 'unknown';
  const commitMsg = (process.env.GITHUB_COMMIT_MESSAGE || '').split('\n')[0].slice(0, 72) || '—';
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');

  // Derive the next row number from how many data rows already exist in the table
  const tableHeaderMarker = '| # | Commit | Message | Author | Date (UTC) | Branch |';
  const existingRows = (content.match(/^\| \d+/gm) || []);
  const nextNum = existingRows.length + 1;

  const newRow = `| ${nextNum} | [\`${shortSha}\`](${shaUrl}) | ${commitMsg} | ${actor} | ${now} | ${branch} |`;

  // If the table header doesn't exist yet, bootstrap the Deployment Log section
  if (!content.includes(tableHeaderMarker)) {
    content += `\n\n## Deployment Log\n\n> ⚙️ **CI-managed section.** One row is appended per merge to \`main\`. Do not edit rows manually.\n\n${tableHeaderMarker}\n|---|--------|---------|--------|------------|--------|"`;
  }

  content += '\n' + newRow;
  await write(filePath, content);
}

// ─────────────────────────────────────────────────────────────────────────────
// VERCEL.md  –  append on pushes (GITHUB_SHA) and include URL when available
// ─────────────────────────────────────────────────────────────────────────────

async function updateVercel() {
  const url = process.env.VERCEL_URL;
  const shaRaw = process.env.GITHUB_SHA;
  if (!shaRaw && !url) {
    console.log('\n⏭️   VERCEL.md – skipped (GITHUB_SHA and VERCEL_URL not set)');
    return;
  }
  console.log('\n☁️   Updating VERCEL.md …');

  const filePath = path.join(ROOT, 'VERCEL.md');
  let content = await readOrEmpty(filePath);

  const sha = (shaRaw || 'unknown').slice(0, 7);
  const branch = process.env.GITHUB_REF_NAME || 'unknown';
  const env = process.env.VERCEL_ENV || 'unknown';
  const deploymentUrl = url
    ? (url.startsWith('http://') || url.startsWith('https://') ? url : `https://${url}`)
    : 'N/A';
  const now = new Date().toISOString();
  const entry = `| ${now} | \`${sha}\` | ${branch} | ${env} | ${deploymentUrl} |`;

  if (!content.includes('## Deployment History')) {
    content += `\n\n## Deployment History\n\n> Entries appended automatically on each push to \`main\`. If \`VERCEL_URL\` is unavailable, URL is recorded as \`N/A\`.\n\n| Deployed At | Commit | Branch | Environment | URL |\n|-------------|--------|--------|-------------|-----|\n`;
  }

  content += entry + '\n';
  await write(filePath, content);
}

// ─────────────────────────────────────────────────────────────────────────────
// Entry point
// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  console.log('🚀  update-docs starting …');
  await generateSitemap();
  await generateCodebaseMap();
  await updateRollback();
  await updateVercel();
  console.log('\n✅  update-docs complete.');
}

main().catch((err) => {
  console.error('update-docs failed:', err);
  process.exit(1);
});
