/**
 * Auto-updating documentation script for the ecocan repo.
 *
 * Behavior:
 *   - SITEMAP.md          → always regenerated by scanning app/** /page.tsx
 *   - CODEBASE-MAP.md     → always regenerated by scanning the full directory tree
 *   - ROLLBACK.md         → appends one entry only when GITHUB_SHA env var is present
 *                           (i.e. when running inside a GitHub Actions deployment step)
 *   - VERCEL.md           → appends one entry when GITHUB_SHA is present (push metadata),
 *                           using VERCEL_URL when available
 *
 * Usage:
 *   npm run docs:update
 *
 * Environment variables (all optional):
 *   GITHUB_SHA        – commit SHA injected by GitHub Actions
 *   GITHUB_REF_NAME   – branch/tag name injected by GitHub Actions
 *   GITHUB_ACTOR      – committer username injected by GitHub Actions
 *   VERCEL_URL        – deployment URL injected by Vercel
 *   VERCEL_ENV        – deployment environment (production|preview|development)
 */

import { promises as fs } from 'fs';
import path from 'path';

const ROOT = process.cwd();

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/** Recursively walk a directory, yielding relative file paths. */
async function walk(dir: string, base = dir): Promise<string[]> {
  const results: string[] = [];
  let entries: import('fs').Dirent[];
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    const rel = path.relative(base, full);
    // skip node_modules, .next, .git, dist, out
    if (['node_modules', '.next', '.git', 'dist', 'out', '.vercel'].includes(entry.name)) continue;
    if (entry.isDirectory()) {
      results.push(...(await walk(full, base)));
    } else {
      results.push(rel);
    }
  }
  return results;
}

/** Safely overwrite a file with the given content. */
async function write(filePath: string, content: string): Promise<void> {
  const dir = path.dirname(filePath);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
  console.log(`  ✅  written: ${path.relative(ROOT, filePath)}`);
}

/** Read a file, returning empty string if it does not exist. */
async function readOrEmpty(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, 'utf8');
  } catch {
    return '';
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// SITEMAP.md  –  always regenerated
// ─────────────────────────────────────────────────────────────────────────────

async function generateSitemap(): Promise<void> {
  console.log('\n📄  Generating SITEMAP.md …');

  const appDir = path.join(ROOT, 'app');
  const allFiles = await walk(appDir, appDir);
  const pageFiles = allFiles.filter((f) => f.endsWith('page.tsx') || f.endsWith('page.ts') || f.endsWith('page.jsx') || f.endsWith('page.js'));

  // Convert file paths to URL routes
  const routes = pageFiles
    .map((f) => {
      // Remove the trailing /page.tsx
      let route = '/' + f.replace(/\/?(page)\.(tsx|ts|jsx|js)$/, '').replace(/\\/g, '/');
      if (route === '/') return '/';
      // Trim trailing slash
      route = route.replace(/\/$/, '') || '/';
      return route;
    })
    .sort();

  // Separate static and dynamic routes
  const staticRoutes = routes.filter((r) => !r.includes('['));
  const dynamicRoutes = routes.filter((r) => r.includes('['));

  const now = new Date().toISOString();

  let md = `# Sitemap\n\n`;
  md += `> Auto-generated by \`scripts/update-docs.ts\` – last updated **${now}**\n`;
  md += `> Do **not** edit this file manually; changes will be overwritten on next run.\n\n`;

  md += `## Static Routes\n\n`;
  md += `| Route | File |\n|-------|------| \n`;
  for (const route of staticRoutes) {
    const file = pageFiles.find((f) => {
      const r = '/' + f.replace(/\/?(page)\.(tsx|ts|jsx|js)$/, '').replace(/\\/g, '/');
      return (r.replace(/\/$/, '') || '/') === route;
    });
    md += `| \`${route}\` | \`app/${file}\` |\n`;
  }

  if (dynamicRoutes.length > 0) {
    md += `\n## Dynamic Routes\n\n`;
    md += `| Route Pattern | File |\n|---------------|------| \n`;
    for (const route of dynamicRoutes) {
      const file = pageFiles.find((f) => {
        const r = '/' + f.replace(/\/?(page)\.(tsx|ts|jsx|js)$/, '').replace(/\\/g, '/');
        return (r.replace(/\/$/, '') || '/') === route;
      });
      md += `| \`${route}\` | \`app/${file}\` |\n`;
    }
  }

  md += `\n## Notes\n\n`;
  md += `- Route patterns containing \`[…]\` are dynamic segments resolved at runtime.\n`;
  md += `- An XML/JSON sitemap for SEO can be auto-generated from this list via \`app/sitemap.ts\`.\n`;
  md += `- Add \`robots.txt\` to \`public/\` and reference \`/sitemap.xml\` for search-engine discoverability.\n`;

  await write(path.join(ROOT, 'SITEMAP.md'), md);
}

// ─────────────────────────────────────────────────────────────────────────────
// CODEBASE-MAP.md  –  always regenerated
// ─────────────────────────────────────────────────────────────────────────────

async function generateCodebaseMap(): Promise<void> {
  console.log('\n🗺️   Generating CODEBASE-MAP.md …');

  const allFiles = await walk(ROOT, ROOT);

  // Group files by top-level directory
  const groups: Record<string, string[]> = {};
  const topLevelFiles: string[] = [];

  for (const f of allFiles) {
    const parts = f.split(path.sep);
    if (parts.length === 1) {
      topLevelFiles.push(f);
    } else {
      const dir = parts[0];
      if (!groups[dir]) groups[dir] = [];
      groups[dir].push(f);
    }
  }

  // Count files per directory
  const dirStats = Object.entries(groups)
    .map(([dir, files]) => ({ dir, count: files.length, files }))
    .sort((a, b) => a.dir.localeCompare(b.dir));

  const now = new Date().toISOString();

  let md = `# Codebase Map\n\n`;
  md += `> Auto-generated by \`scripts/update-docs.ts\` – last updated **${now}**\n`;
  md += `> Do **not** edit this file manually; changes will be overwritten on next run.\n\n`;

  md += `## Stack Overview\n\n`;
  md += `| Layer | Technology |\n|-------|-----------|\n`;
  md += `| Framework | Next.js 14 (App Router) |\n`;
  md += `| Language | TypeScript 5 + React 18 |\n`;
  md += `| Styling | Tailwind CSS 3 + Radix UI primitives |\n`;
  md += `| Animation | Framer Motion + Embla Carousel |\n`;
  md += `| Forms | react-hook-form + zod |\n`;
  md += `| Analytics | @vercel/analytics |\n`;
  md += `| Deployment | Vercel |\n\n`;

  md += `## Root-level Config Files\n\n`;
  const configFiles = topLevelFiles.filter((f) =>
    ['.env', '.env.local', '.eslintrc', '.eslintrc.json', '.eslintrc.js',
      'next.config', 'next.config.mjs', 'next.config.js', 'tailwind.config.ts',
      'tailwind.config.js', 'postcss.config.mjs', 'postcss.config.js',
      'tsconfig.json', 'package.json', 'package-lock.json', 'yarn.lock',
      'pnpm-lock.yaml', '.gitignore', 'README.md', 'VERCEL.md', 'CLAUDE.md',
      'ROLLBACK.md', 'SITEMAP.md', 'CODEBASE-MAP.md'].some((c) => f.endsWith(c))
  );
  for (const f of configFiles.sort()) {
    md += `- \`${f}\`\n`;
  }

  md += `\n## Directory Structure\n\n`;

  for (const { dir, count, files } of dirStats) {
    md += `### \`${dir}/\` (${count} files)\n\n`;

    // Show up to 2 levels deep
    const subDirs: Record<string, number> = {};
    for (const f of files) {
      const parts = f.split(path.sep);
      if (parts.length >= 2) {
        const sub = parts[1];
        subDirs[sub] = (subDirs[sub] || 0) + 1;
      }
    }

    if (Object.keys(subDirs).length > 0) {
      for (const [sub, cnt] of Object.entries(subDirs).sort()) {
        md += `- \`${dir}/${sub}\` – ${cnt} file${cnt !== 1 ? 's' : ''}\n`;
      }
    } else {
      // flat – list all files
      for (const f of files.sort()) {
        md += `- \`${f}\`\n`;
      }
    }
    md += '\n';
  }

  md += `## Data & Content Flow\n\n`;
  md += `1. **Routing** – Each folder under \`app/\` maps to a URL segment via Next.js App Router.\n`;
  md += `2. **Page composition** – Pages import persona-specific content from \`components/contents/{persona}/\`.\n`;
  md += `3. **Shared layout** – \`app/layout.tsx\` wraps every page with Navbar (\`components/shared/navbar/\`) and Footer.\n`;
  md += `4. **Design system** – \`components/ui/\` holds Radix + Tailwind primitives reused everywhere.\n`;
  md += `5. **Forms** – \`react-hook-form\` + \`zod\` schemas; form components live in \`components/shared/\`.\n`;
  md += `6. **Utilities** – Hooks and helpers in \`lib/\`; TypeScript models in \`types/\`.\n\n`;

  await write(path.join(ROOT, 'CODEBASE-MAP.md'), md);
}

// ─────────────────────────────────────────────────────────────────────────────
// ROLLBACK.md  –  append only when GITHUB_SHA is present
// ─────────────────────────────────────────────────────────────────────────────

async function updateRollback(): Promise<void> {
  const sha = process.env.GITHUB_SHA;
  if (!sha) {
    console.log('\n⏭️   ROLLBACK.md – skipped (GITHUB_SHA not set)');
    return;
  }

  console.log('\n🔄  Updating ROLLBACK.md …');

  const filePath = path.join(ROOT, 'ROLLBACK.md');
  let existing = await readOrEmpty(filePath);

  const shortSha = sha.slice(0, 7);
  const branch = process.env.GITHUB_REF_NAME || 'unknown';
  const actor = process.env.GITHUB_ACTOR || 'unknown';
  const now = new Date().toISOString();
  const entry = `| \`${shortSha}\` | ${now} | ${branch} | ${actor} |`;

  // Ensure the deployment log table exists
  if (!existing.includes('## Deployment Log')) {
    existing += `

## Deployment Log

> Entries appended automatically on each push to \`main\` via GitHub Actions.\n> To roll back: \`git revert <SHA>\` or open a PR reverting the commit, then deploy.

| Commit | Deployed At | Branch | Actor |
|--------|-------------|--------|-------|
`;
  }

  existing += entry + '\n';
  await write(filePath, existing);
}

// ─────────────────────────────────────────────────────────────────────────────
// VERCEL.md  –  append on pushes (GITHUB_SHA) and include URL when available
// ─────────────────────────────────────────────────────────────────────────────

async function updateVercel(): Promise<void> {
  const url = process.env.VERCEL_URL;
  const shaRaw = process.env.GITHUB_SHA;
  if (!shaRaw && !url) {
    console.log('\n⏭️   VERCEL.md – skipped (GITHUB_SHA and VERCEL_URL not set)');
    return;
  }

  console.log('\n☁️   Updating VERCEL.md …');

  const filePath = path.join(ROOT, 'VERCEL.md');
  let existing = await readOrEmpty(filePath);

  const sha = shaRaw?.slice(0, 7) || 'unknown';
  const branch = process.env.GITHUB_REF_NAME || 'unknown';
  const env = process.env.VERCEL_ENV || 'unknown';
  const deploymentUrl = url ? (url.startsWith('http://') || url.startsWith('https://') ? url : `https://${url}`) : 'N/A';
  const now = new Date().toISOString();
  const entry = `| ${now} | \`${sha}\` | ${branch} | ${env} | ${deploymentUrl} |`;

  if (!existing.includes('## Deployment History')) {
    existing += `

## Deployment History

> Entries appended automatically on each push to \`main\`. If \`VERCEL_URL\` is unavailable, URL is recorded as \`N/A\`.

| Deployed At | Commit | Branch | Environment | URL |
|-------------|--------|--------|-------------|-----|
`;
  }

  existing += entry + '\n';
  await write(filePath, existing);
}

// ─────────────────────────────────────────────────────────────────────────────
// Entry point
// ─────────────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log('🚀  update-docs starting …');

  await generateSitemap();
  await generateCodebaseMap();
  await updateRollback();
  await updateVercel();

  console.log('\n✅  update-docs complete.');
}

main().catch((err) => {
  console.error('update-docs failed:', err);
  process.exit(1);
});
