/**
 * scripts/update-docs.ts
 *
 * Auto-regenerates these repo-level markdown files:
 *   SITEMAP.md       – scanned from app/ page.tsx files
 *   CODEBASE-MAP.md  – scanned from app/, components/, lib/, types/
 *   ROLLBACK.md      – appends a new entry per run (commit hash, author, date)
 *   VERCEL.md        – appends a deployment history entry per run
 *   CLAUDE.md        – keeps header static, updates "Last refreshed" stamp
 *
 * Usage:
 *   npx ts-node scripts/update-docs.ts
 *
 * Environment variables (all optional):
 *   GITHUB_SHA         – current commit hash
 *   GITHUB_ACTOR       – commit author GitHub login
 *   GITHUB_REF_NAME    – branch name
 *   VERCEL_URL         – production deployment URL (set as a repo secret)
 *   VERCEL_PROJECT_ID  – Vercel project ID (set as a repo secret)
 */

import { promises as fs } from "fs";
import * as path from "path";

const ROOT = process.cwd();
const NOW = new Date().toISOString();
const SHA = (process.env.GITHUB_SHA ?? "local").slice(0, 7);
const ACTOR = process.env.GITHUB_ACTOR ?? "local";
const BRANCH = process.env.GITHUB_REF_NAME ?? "local";
const VERCEL_URL = process.env.VERCEL_URL ?? "(not configured)";
const VERCEL_PROJECT_ID = process.env.VERCEL_PROJECT_ID ?? "(not configured)";

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function readFile(filePath: string): Promise<string> {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch {
    return "";
  }
}

async function writeFile(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, "utf8");
  console.log(`  ✅  Written: ${path.relative(ROOT, filePath)}`);
}

/**
 * Walk a directory recursively and collect all file paths.
 */
async function walk(dir: string, ignore: string[] = []): Promise<string[]> {
  const results: string[] = [];
  let entries: string[] = [];
  try {
    entries = await fs.readdir(dir);
  } catch {
    return results;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry);
    if (ignore.some((ig) => full.includes(ig))) continue;
    const stat = await fs.stat(full);
    if (stat.isDirectory()) {
      results.push(...(await walk(full, ignore)));
    } else {
      results.push(full);
    }
  }
  return results;
}

// ─── SITEMAP.md ──────────────────────────────────────────────────────────────

async function generateSitemap(): Promise<string> {
  const appDir = path.join(ROOT, "app");
  const files = await walk(appDir, ["node_modules", ".next"]);
  const pages = files
    .filter((f) => f.endsWith("page.tsx") || f.endsWith("page.ts") || f.endsWith("page.jsx"))
    .map((f) => path.relative(appDir, f));

  const topLevel: string[] = [];
  const dynamic: string[] = [];

  for (const p of pages.sort()) {
    const route = "/" + p
      .replace(/\\/g, "/")
      .replace(/\/page\.(tsx|ts|jsx|js)$/, "")
      .replace(/^page\.(tsx|ts|jsx|js)$/, "");

    const cleanRoute = route === "/" ? "/" : route;

    if (cleanRoute.includes("[")) {
      dynamic.push(`- \`${cleanRoute}\` – dynamic route (\`app/${p}\`)`);
    } else {
      topLevel.push(`- \`${cleanRoute}\` – \`app/${p}\``);
    }
  }

  return `# Ecocan Content Sitemap\n\n> Auto-generated by \`scripts/update-docs.ts\` on ${NOW}.\n> Last commit: \`${SHA}\` by \`${ACTOR}\` on \`${BRANCH}\`.\n\n## Top-level routes\n\n${topLevel.join("\n")}\n\n## Dynamic routes\n\n${dynamic.join("\n")}\n\n## Notable content sections\n\n- Solutions sections in \`app/solutions/sections/*\` map to logical subpages and personas.\n- Content verticals in \`components/contents/*\` drive persona-specific journeys.\n\nFor SEO XML sitemaps, add \`app/sitemap.ts\` or \`app/sitemap.xml/route.ts\` mirroring this structure.\n`;
}

// ─── CODEBASE-MAP.md ─────────────────────────────────────────────────────────

async function generateCodebaseMap(): Promise<string> {
  const IGNORE = ["node_modules", ".next", ".git", "public"];

  async function treeSection(dir: string, label: string): Promise<string[]> {
    const files = await walk(path.join(ROOT, dir), IGNORE);
    const rows = files
      .map((f) => path.relative(ROOT, f))
      .map((f) => `  - \`${f}\``)
      .slice(0, 200);
    return [`### ${label} (\`${dir}/\`)`, "", ...rows, ""];
  }

  const appLines = await treeSection("app", "Pages & Routes");
  const compLines = await treeSection("components", "Components");
  const libLines = await treeSection("lib", "Utilities & Hooks");
  const typeLines = await treeSection("types", "TypeScript Types");

  const packageJson = JSON.parse(await readFile(path.join(ROOT, "package.json")));
  const deps = Object.keys(packageJson.dependencies ?? {}).join(", ");
  const devDeps = Object.keys(packageJson.devDependencies ?? {}).join(", ");

  return `# Ecocan Codebase Map\n\n> Auto-generated by \`scripts/update-docs.ts\` on ${NOW}.\n> Last commit: \`${SHA}\` by \`${ACTOR}\` on \`${BRANCH}\`.\n\n## Stack overview\n\n- **Framework**: Next.js ${packageJson.dependencies?.next ?? "14"} (App Router)\n- **Language**: TypeScript + React 18\n- **Styling**: Tailwind CSS + \`tailwind-merge\` + \`class-variance-authority\`\n- **UI primitives**: Radix UI components + Lucide icons\n- **Forms**: \`react-hook-form\` + \`zod\` + \`@hookform/resolvers\`\n- **Motion**: \`framer-motion\`\n- **Analytics**: \`@vercel/analytics\`\n\n### Dependencies\n\`\`\`\n${deps}\n\`\`\`\n\n### Dev Dependencies\n\`\`\`\n${devDeps}\n\`\`\`\n\n---\n\n## File tree\n\n${appLines.join("\n")}\n${compLines.join("\n")}\n${libLines.join("\n")}\n${typeLines.join("\n")}\n\n## Data & content flow\n\n- Pages in \`app/\` compose content from \`components/contents\` and shared blocks.\n- Forms use \`react-hook-form\` + \`zod\` for validation.\n- Navigation and layout are centralized in \`app/layout.tsx\` and \`components/shared/navbar\`.\n`;
}

// ─── ROLLBACK.md ─────────────────────────────────────────────────────────────

async function generateRollback(): Promise<string> {
  const existing = await readFile(path.join(ROOT, "ROLLBACK.md"));

  const match = existing.match(/(## Deployment Log[\s\S]*?)(?=## How to roll back|$)/);
  const existingLog = match ? match[1].trim() : "## Deployment Log\n\n> CI appends one entry per run.";

  const newEntry = `- \`${SHA}\` – ${NOW} – pushed by \`${ACTOR}\` on \`${BRANCH}\``;

  const updatedLog = existingLog.replace(
    /(## Deployment Log\n+(?:> [^\n]*\n+)?)/,
    `$1${newEntry}\n`
  );

  return `# Ecocan Rollback Guide\n\n> Auto-updated by \`scripts/update-docs.ts\` on ${NOW}.\n\n## How to roll back\n\n1. Identify the last known good commit from the **Deployment Log** below.\n2. Create a rollback branch:\n   \`\`\`bash\n   git checkout -b rollback/<commit-sha> <commit-sha>\n   git push origin rollback/<commit-sha>\n   \`\`\`\n3. Open a PR titled **"Rollback to <commit-sha>"** against \`main\`.\n4. Verify the Vercel Preview deployment.\n5. Merge to \`main\` and confirm production health.\n\n## Rollback checklist\n\n- [ ] Identify the target commit in the log below\n- [ ] Create rollback branch from that commit\n- [ ] Open PR against \`main\`\n- [ ] Verify preview deployment on Vercel\n- [ ] Check key pages: \`/\`, \`/solutions\`, \`/eco-friendly-cans\`, \`/news\`\n- [ ] Merge and confirm production\n\n${updatedLog}\n\n## How to roll forward\n\nIf the rollback introduced new issues, simply revert the rollback PR and redeploy \`main\`.\n`;
}

// ─── VERCEL.md ───────────────────────────────────────────────────────────────

async function generateVercel(): Promise<string> {
  const existing = await readFile(path.join(ROOT, "VERCEL.md"));

  const match = existing.match(/(## Deployment History[\s\S]*?)$/);
  const existingHistory = match
    ? match[1].trim()
    : "## Deployment History\n\n> CI appends one entry per deployment.";

  const newEntry = `- \`${SHA}\` – ${NOW} – branch: \`${BRANCH}\` – actor: \`${ACTOR}\` – url: ${VERCEL_URL}`;

  const updatedHistory = existingHistory.replace(
    /(## Deployment History\n+(?:> [^\n]*\n+)?)/,
    `$1${newEntry}\n`
  );

  return `# Ecocan Vercel Deployment Notes\n\n> Auto-updated by \`scripts/update-docs.ts\` on ${NOW}.\n\n## Expected setup\n\n- Connect \`rauell1/ecocan\` to a Vercel project with the **Next.js** framework preset.\n- Node 18+ runtime; install via Vercel defaults.\n- Build command: \`next build\` (from \`package.json\`).\n- Output: Next.js App Router (no custom \`output\` set in \`next.config.mjs\`).\n\n## Project metadata\n\n| Field | Value |\n|---|---|\n| Project ID | \`${VERCEL_PROJECT_ID}\` |\n| Production URL | ${VERCEL_URL} |\n| Framework | Next.js 14 App Router |\n| Build command | \`next build\` |\n\n## Environment variables\n\nSet the following in Vercel project settings → **Environment Variables**:\n\n| Name | Environments | Purpose |\n|---|---|---|\n| \`VERCEL_URL\` | production, preview | Available automatically from Vercel |\n| Any form/API secrets | production | Third-party integrations (e.g., mail, CMS) |\n\n## Analytics\n\n\`@vercel/analytics\` is included – enable Vercel Analytics in the dashboard.\n\n## Automatic updates\n\nThis file is updated by the \`docs-update\` GitHub Actions workflow on every push to \`main\`.\nTo include the Vercel deployment URL, add \`VERCEL_URL\` as a repository secret.\n\n${updatedHistory}\n`;
}

// ─── CLAUDE.md ───────────────────────────────────────────────────────────────

async function generateClaude(): Promise<string> {
  return `# Ecocan – AI Assistant Guidelines\n\n> Auto-updated timestamp: ${NOW}. Core content is manually maintained.\n\n## Stack context for AI assistants\n\nWhen generating or editing code for this repo, note:\n\n- **Framework**: Next.js 14 App Router (\`app/\` directory)\n- **Language**: TypeScript, strict mode\n- **Styling**: Tailwind CSS (utility-first; no CSS modules)\n- **UI primitives**: Radix UI + custom wrappers in \`components/ui/\`\n- **Forms**: \`react-hook-form\` + \`zod\` schemas\n- **Icons**: \`lucide-react\`\n- **Motion**: \`framer-motion\`\n\n## Coding guidelines\n\n- Prefer editing existing components in \`components/\` over creating one-off variants.\n- Follow the established folder structure when adding new pages (\`app/<route>/page.tsx\`).\n- Reuse \`components/ui\` primitives and \`components/shared\` building blocks.\n- Use \`@/*\` path alias for all imports (configured in \`tsconfig.json\`).\n- Keep new dependencies lightweight and justified; check \`package.json\` first.\n- All new components should be typed – no \`any\` types.\n\n## File structure conventions\n\n| What | Where |\n|---|---|\n| New page | \`app/<route>/page.tsx\` |\n| Page-specific component | \`app/<route>/components/<component>.tsx\` |\n| Shared reusable component | \`components/shared/<component>.tsx\` |\n| UI primitive | \`components/ui/<primitive>.tsx\` |\n| Shared hook or utility | \`lib/<hook-or-util>.ts\` |\n| Type definition | \`types/<name>.ts\` |\n\n## Safety & review\n\n- Run \`npm run lint\` and \`npm run build\` before submitting any PR.\n- Keep PRs small and focused; one feature or fix per PR.\n- Avoid committing secrets, credentials, or personally identifiable information.\n- If unsure about a pattern, check an existing component for reference.\n\n## Auto-update strategy\n\nThis file is regenerated by \`scripts/update-docs.ts\` (triggered by the \`docs-update\` workflow).\nThe guidelines above are static; only the timestamp refreshes automatically.\nTo update the guidelines, edit \`scripts/update-docs.ts\` directly.\n`;
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  console.log(`\n🔄  update-docs.ts — ${NOW}`);
  console.log(`    commit=${SHA}  actor=${ACTOR}  branch=${BRANCH}\n`);

  const tasks: Array<{ name: string; path: string; fn: () => Promise<string> }> = [
    { name: "SITEMAP.md",      path: path.join(ROOT, "SITEMAP.md"),      fn: generateSitemap },
    { name: "CODEBASE-MAP.md", path: path.join(ROOT, "CODEBASE-MAP.md"), fn: generateCodebaseMap },
    { name: "ROLLBACK.md",     path: path.join(ROOT, "ROLLBACK.md"),     fn: generateRollback },
    { name: "VERCEL.md",       path: path.join(ROOT, "VERCEL.md"),       fn: generateVercel },
    { name: "CLAUDE.md",       path: path.join(ROOT, "CLAUDE.md"),       fn: generateClaude },
  ];

  for (const task of tasks) {
    try {
      const content = await task.fn();
      await writeFile(task.path, content);
    } catch (err) {
      console.error(`  ❌  Failed to generate ${task.name}:`, err);
      process.exit(1);
    }
  }

  console.log("\n✅  All docs updated.\n");
}

main().catch((err) => {
  console.error("update-docs failed:", err);
  process.exit(1);
});
